{% set name = "shade" %}
{% set version = "1.28.0" %}
{% set sha256 = "d2d5986622b69deaeff6ba2713a022f7193f37140071b5f56e477d68672d1a9c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - six
    - munch
    - decorator
    - jmespath
    - jsonpatch
    - keystoneauth1
    - os-client-config
    - requestsexceptions
    - dogpile.cache
    - futures  # [py27]
    - simplejson
    - netifaces
    - python-ironicclient

test:
  imports:
    - shade

about:
  home: https://docs.openstack.org/developer/shade/
  license: Apache 2.0
  license_file: LICENSE
  summary: Client library for OpenStack containing Infra business logic
  dev_url: https://github.com/openstack-infra/shade.git
  doc_url: https://docs.openstack.org/shade/latest/

extra:
  recipe-maintainers:
    - brainstorm 
