{% set name = "shade" %}
{% set version = "1.27.0" %}
{% set sha256 = "11a1602e6f937ff43363fafe2cba7d416a5cecf5f9131e137b1363392e3c3e66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py3k]

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - six
    - munch
    - decorator
    - jmespath
    - jsonpatch
    - keystoneauth1
    - os-client-config
    - requestsexceptions
    - dogpile.cache
    - futures
    - simplejson
    - netifaces
    - python-ironicclient

test:
  imports:
    - shade

about:
  home: https://docs.openstack.org/developer/shade/
  license: Apache 2.0
  license_file: LICENSE
  summary: Client library for OpenStack containing Infra business logic
  dev_url: https://github.com/openstack-infra/shade.git
  doc_url: https://docs.openstack.org/shade/latest/

extra:
  recipe-maintainers:
    - brainstorm 
