{% set name = "shade" %}
{% set version = "1.32.0" %}
{% set sha256 = "514326efb926cea5b77efe06a69bcdc0bdb996c1bc95bd2349638cc21b772430" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - pbr
  run:
    - python
    - six
    - munch
    - decorator
    - jmespath
    - jsonpatch
    - keystoneauth1
    - os-client-config
    - requestsexceptions
    - dogpile.cache
    - futures  # [py27]
    - simplejson
    - netifaces
    - python-ironicclient

test:
  imports:
    - shade

about:
  home: https://docs.openstack.org/developer/shade/
  license: Apache 2.0
  license_file: LICENSE
  summary: Client library for OpenStack containing Infra business logic
  dev_url: https://github.com/openstack-infra/shade.git
  doc_url: https://docs.openstack.org/shade/latest/

extra:
  recipe-maintainers:
    - brainstorm
