travis:
  secure:
    BINSTAR_TOKEN: eFzwFrC+BcN7/9hoC+1Ukh1eTNI60kFNkpMszaH8B713MAiiCWmMW2k2arwLBVZckxIxd69K8vWyBHxfYa1gyxQBqfgAHfE0/ieZ483upOaxBRFe06cuF68Qnr5vpaj6WUOF5BLH8TW2tScqVSBjGkQEIIjbZZDYUMkqHShrvBLaQ0bbrlpjuuUGyZ7dL8K5fiNPK5pNMl1k2G2CHI79xor6m5bcN+1mqXYoi/Gr6Jq+qxIOUSSd9od9ak99UL7BiOnUWDgfgZME0rL80sbULXEwAh0ZWB6Hpbj6Ny6TPXOsZrM1APsF1PQHqp8fD1akv5JlcTvTidkHtiDNrJI0wr+pxw3AsReau2vyJ/wHbmAYiJEDObeS6eQOwNgRihTBh8awqQskPdJcpNpm7WRu6+rFaxlD3YGoxmCyWf7J7E7i8U5eDjDJeoWEMJzHd4qTz23NQO1zcNdUSJdyBUUCzVoK08xdG5R/b/c9nHCpDsq8GxINLg/i5osuXm4aTfTgJv7cW9C6gs0fxjgqe9lhUDZsUMy4sK98qt/ehjR2qVZIjxrKPB4+hSWTf8GrBmgYZgPgLNqa5U6Kh5fMBID9NpCYsmZIjfbf4lB1DfG++Cu6VflZRAqYOleg02zJ9YnNY5TcPu4acYqlRn06A4Hds40V8eBwy4m3joo2ZxTpdFA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
